### ISSUE TITLE
The port number is random

### ISSUE THREAD

**Issue by claretnnamocha** [pytonik/pytonik#20]
Right now the port number for this framework is generated randomly and this makes it difficult to keep track of.  
Could the port number be static eg `1111` so once the server is started it is served on `localhost:1111`?  
Also, a new option for the `pytonik-server` command could be created? This takes a custom port number eg `pytonik-server --port=8356` to make the code serve on the port number of your choice

**Comment by emmamartins** [comment]
Noted, The default port 6060.
